# CyteOnto quick tutorial

Compare author cell-type labels against one or more algorithm predictions using the Cell Ontology.

This notebook uses the **primary** model pair (Nebius for descriptions and embeddings) with an optional **fallback** pair (Fireworks / OpenRouter) configured on `CyteOnto`.

Set these in `.env` at the repo root (see `cyteonto/config.py` → `PROVIDER_API_KEY_ENV`):

- `NEBIUS_API_KEY`
- `FIREWORKS_API_KEY` (fallback LLM)
- `OPENROUTER_API_KEY` (fallback embeddings)

Optional: `NCBI_API_KEY` for PubMed tool use during description generation. Default is `False`.

In [ ]:
import sys
from pathlib import Path

sys.path.insert(0, str(Path("..").resolve()))

from dotenv import load_dotenv

load_dotenv(Path("..") / ".env")

In [2]:
import os

import numpy as np
import pandas as pd
from pydantic_ai import Agent
from pydantic_ai.models.openai import OpenAIChatModel
from pydantic_ai.providers.openai import OpenAIProvider

from cyteonto import CyteOnto, EmbdConfig, LlmConfig
from cyteonto.config import Config
from cyteonto.cyteonto import _hungarian_match_mean

In [3]:
cfg = Config()

LLM_BASE_URLS = {
    "nebius": "https://api.tokenfactory.nebius.com/v1/",
    "fireworks": "https://api.fireworks.ai/inference/v1",
    "openrouter": "https://openrouter.ai/api/v1/",
    "together": "https://api.together.xyz/v1/",
}


def build_agent(provider: str, model: str) -> Agent:
    env_var = cfg.PROVIDER_API_KEY_ENV[provider]
    api_key = os.environ[env_var]
    return Agent(
        OpenAIChatModel(
            model,
            provider=OpenAIProvider(
                api_key=api_key,
                base_url=LLM_BASE_URLS[provider],
            ),
        )
    )


primary_agent = build_agent(cfg.PRIMARY_LLM_PROVIDER, cfg.PRIMARY_LLM_MODEL)
fallback_agent = build_agent(cfg.FALLBACK_LLM_PROVIDER, cfg.FALLBACK_LLM_MODEL)

primary_embedding = EmbdConfig(
    provider=cfg.PRIMARY_EMBEDDING_PROVIDER,
    model=cfg.PRIMARY_EMBEDDING_MODEL,
    apiKey=os.environ[cfg.PROVIDER_API_KEY_ENV[cfg.PRIMARY_EMBEDDING_PROVIDER]],
    modelSettings={},
)

fallback_embedding = EmbdConfig(
    provider=cfg.FALLBACK_EMBEDDING_PROVIDER,
    model=cfg.FALLBACK_EMBEDDING_MODEL,
    apiKey=os.environ[cfg.PROVIDER_API_KEY_ENV[cfg.FALLBACK_EMBEDDING_PROVIDER]],
)

llm = LlmConfig(provider=cfg.PRIMARY_LLM_PROVIDER, model=cfg.PRIMARY_LLM_MODEL)
fallback_llm = LlmConfig(
    provider=cfg.FALLBACK_LLM_PROVIDER, model=cfg.FALLBACK_LLM_MODEL
)

## Prepare ontology cache

`from_config` ensures Cell Ontology descriptions and embeddings exist under `cyteonto/data/` for this model pair. The first run may take several minutes.

In [ ]:
cyto = await CyteOnto.from_config(
    agent=primary_agent,
    embedding=primary_embedding,
    llm=llm,
    fallback_agent=fallback_agent,
    fallback_embedding=fallback_embedding,
    fallback_llm=fallback_llm,
    use_pubmed_tool=False,  # bool(os.getenv("NCBI_API_KEY")),
)

## Run a comparison

Each row is one `(algorithm, pair_index)` with ontology matches and a CyteScore similarity. Reuse `run_id` to benefit from on-disk caches.

In [ ]:
author_labels = [
    "animal stem cell",
    "BFU-E",
    "neutrophilic granuloblast",
]

algorithms = {
    "method_a": ["stem cell", "blast forming unit erythroid", "spermatogonium"],
    "method_b": ["neuronal receptor cell", "stem cell", "ovum"],
}

df = await cyto.compare(
    author_labels=author_labels,
    algorithms=algorithms,
    run_id="quick_tutorial_demo",
    metric="cosine_kernel",
)

In [6]:
df

,run_id,algorithm,pair_index,author_label,algorithm_label,author_ontology_id,author_ontology_name,author_embedding_similarity,algorithm_ontology_id,algorithm_ontology_name,algorithm_embedding_similarity,cytescore_similarity,similarity_method
0,quick_tutorial_demo,method_a,0,animal stem cell,stem cell,CL:0002248,pluripotent stem cell,0.8119,CL:0000034,stem cell,0.8255,0.5450,cytescore
1,quick_tutorial_demo,method_a,1,BFU-E,blast forming unit erythroid,CL:0000038,erythroid progenitor cell,0.8626,CL:0000038,erythroid progenitor cell,0.8249,1.0000,cytescore
2,quick_tutorial_demo,method_a,2,neutrophilic granuloblast,spermatogonium,CL:0000042,neutrophilic myeloblast,0.8360,CL:0000020,spermatogonium,0.9061,0.1077,cytescore
3,quick_tutorial_demo,method_b,0,animal stem cell,neuronal receptor cell,CL:0002248,pluripotent stem cell,0.8119,CL:0000006,neuronal receptor cell,0.8635,0.0671,cytescore
4,quick_tutorial_demo,method_b,1,BFU-E,stem cell,CL:0000038,erythroid progenitor cell,0.8626,CL:0000034,stem cell,0.7925,0.1231,cytescore
5,quick_tutorial_demo,method_b,2,neutrophilic granuloblast,ovum,CL:0000042,neutrophilic myeloblast,0.8360,CL:0000025,egg cell,0.8905,0.0837,cytescore

In [7]:
print("run_id:", df["run_id"].iloc[0])
print("model pair usage:", cyto.model_pair_usage.to_status_dict())
print("LLM usage:", cyto.usage.model_dump())

run_id: quick_tutorial_demo
model pair usage: {'llmTier': 'primary', 'embeddingTier': 'primary', 'llmProvider': 'nebius', 'llmModel': 'moonshotai/Kimi-K2.6', 'embeddingProvider': 'nebius', 'embeddingModel': 'Qwen/Qwen3-Embedding-8B'}
LLM usage: {'agentName': 'CyteOnto', 'modelName': 'moonshotai/Kimi-K2.6', 'requests': 18, 'inputTokens': 8859, 'outputTokens': 1862, 'totalTokens': 10721, 'toolUsage': {'final_result': 19}}

## Compound label scoring

Mixture labels (doublets, mixed populations) are decomposed by the LLM into cell-type parts before scoring. Each input pair still produces **one row**.

For compound pairs (`similarity_method == "cytescore_compound"`):

1. Build an **m×n** cytescore matrix `S` between author parts (rows) and algorithm parts (columns).
2. Run **max-weight bipartite matching** (Hungarian algorithm): pick `k = min(m, n)` one-to-one pairs that maximize total score.
3. **Match mean** = average score of the assigned pairs.
4. If **m ≠ n**, multiply by **coverage** = `min(m, n) / max(m, n)`.

Ontology IDs and names in the result list only the **matched** assignment pairs (semicolon-separated when `k > 1`).

| Scenario | m×n | Illustrative score |
|----------|-----|--------------------|
| Same compound (two overlap) | 2×2 | ~1.0 |
| One shared type | 2×2 | ~0.5 |
| No shared types | 2×2 | ~0.07 |
| Partial overlap, extra author type | 3×2 | ~0.35 |
| Author doublet vs single type | 2×1 | best match × 0.5 |

The next cell runs these matrices with `_hungarian_match_mean` using illustrative scores (no API calls). The section after that runs live comparisons for the same scenarios.

### Synthetic scoring examples (no API)

Scores below are **illustrative** cytescores placed in `S` to show how the metric behaves. Live labels in the next section use the real pipeline (decompose → embed → match → Hungarian).

In [8]:
def hungarian_demo(scenario: str, scores: list[list[float]]) -> dict:
    matrix = np.array(scores, dtype=np.float64)
    m, n = matrix.shape
    final, assignments = _hungarian_match_mean(matrix)
    return {
        "scenario": scenario,
        "m": m,
        "n": n,
        "coverage": min(m, n) / max(m, n) if max(m, n) else 0.0,
        "assignments": assignments,
        "illustrative_cytescore": round(final, 4),
        "matrix": matrix,
    }


demo_scenarios = [
    ("2x1_coverage", [[0.05], [0.92]]),
    ("2x2_two_overlap", [[0.98, 0.06], [0.05, 0.97]]),
    ("2x2_one_overlap", [[0.98, 0.05], [0.06, 0.08]]),
    ("2x2_zero_overlap", [[0.06, 0.05], [0.08, 0.07]]),
    ("3x2_one_overlap", [[0.98, 0.05], [0.06, 0.08], [0.05, 0.07]]),
]

demos = [hungarian_demo(name, matrix) for name, matrix in demo_scenarios]

demo_df = pd.DataFrame(
    [
        {
            "scenario": d["scenario"],
            "m": d["m"],
            "n": d["n"],
            "coverage": round(d["coverage"], 4),
            "assignments": d["assignments"],
            "illustrative_cytescore": d["illustrative_cytescore"],
        }
        for d in demos
    ]
)
demo_df

           scenario  m  n  coverage       assignments  illustrative_cytescore
0      2x1_coverage  2  1    0.5000          [(1, 0)]                  0.4600
1   2x2_two_overlap  2  2    1.0000  [(0, 0), (1, 1)]                  0.9750
2   2x2_one_overlap  2  2    1.0000  [(0, 0), (1, 1)]                  0.5300
3  2x2_zero_overlap  2  2    1.0000  [(0, 0), (1, 1)]                  0.0650
4   3x2_one_overlap  3  2    0.6667  [(0, 0), (1, 1)]                  0.3533

### Live compound comparisons

Each row below is a deliberate scenario. After `compare`, a `scenario` column is attached for readability.

In [ ]:
compound_scenarios = [
    ("2x1_coverage", "AT2 cell-plasma cell doublet", "Plasma cell"),
    ("2x2_two_overlap", "AT2 cell-plasma cell doublet", "AT2 cell / Plasma cell"),
    ("2x2_one_overlap", "AT2 cell-plasma cell doublet", "AT2 cell / T cell"),
    ("2x2_zero_overlap", "AT2 cell-plasma cell doublet", "T cell / B cell"),
    ("3x2_one_overlap", "AT2 cell / plasma cell / NK cell", "AT2 cell / T cell"),
    ("simple_control", "T cell", "T cell"),
]

compound_author_labels = [author for _, author, _ in compound_scenarios]
compound_algorithm_labels = [algo for _, _, algo in compound_scenarios]

compound_df = await cyto.compare(
    author_labels=compound_author_labels,
    algorithms={"scenarios": compound_algorithm_labels},
    run_id="quick_tutorial_compound",
    metric="cosine_kernel",
)
compound_df.insert(0, "scenario", [name for name, _, _ in compound_scenarios])

In [10]:
compound_df

,scenario,run_id,algorithm,pair_index,author_label,algorithm_label,author_ontology_id,author_ontology_name,author_embedding_similarity,algorithm_ontology_id,algorithm_ontology_name,algorithm_embedding_similarity,cytescore_similarity,similarity_method
0,2x1_coverage,quick_tutorial_compound,scenarios,0,AT2 cell-plasma cell doublet,Plasma cell,CL:0000946,antibody secreting cell,0.9124,CL:0000946,antibody secreting cell,0.9023,0.5000,cytescore_compound
1,2x2_two_overlap,quick_tutorial_compound,scenarios,1,AT2 cell-plasma cell doublet,AT2 cell / Plasma cell,CL:0002063;CL:0000946,pulmonary alveolar type 2 cell;antibody secret...,0.9124,CL:0002063;CL:0000946,pulmonary alveolar type 2 cell;antibody secret...,0.8979,1.0000,cytescore_compound
2,2x2_one_overlap,quick_tutorial_compound,scenarios,2,AT2 cell-plasma cell doublet,AT2 cell / T cell,CL:0002063;CL:0000946,pulmonary alveolar type 2 cell;antibody secret...,0.9124,CL:0002063;CL:0000084,pulmonary alveolar type 2 cell;T cell,0.8684,0.5984,cytescore_compound
3,2x2_zero_overlap,quick_tutorial_compound,scenarios,3,AT2 cell-plasma cell doublet,T cell / B cell,CL:0002063;CL:0000946,pulmonary alveolar type 2 cell;antibody secret...,0.9124,CL:0000084;CL:0000236,T cell;B cell,0.8576,0.3334,cytescore_compound
4,3x2_one_overlap,quick_tutorial_compound,scenarios,4,AT2 cell / plasma cell / NK cell,AT2 cell / T cell,CL:0002063;CL:0000623,pulmonary alveolar type 2 cell;natural killer ...,0.8855,CL:0002063;CL:0000084,pulmonary alveolar type 2 cell;T cell,0.8684,0.4121,cytescore_compound
5,simple_control,quick_tutorial_compound,scenarios,5,T cell,T cell,CL:0000084,T cell,0.8753,CL:0000084,T cell,0.8435,1.0000,cytescore

In [11]:
summary_cols = [
    "scenario",
    "author_label",
    "algorithm_label",
    "author_ontology_name",
    "algorithm_ontology_name",
    "cytescore_similarity",
    "similarity_method",
]

live_summary = compound_df[summary_cols].rename(
    columns={"cytescore_similarity": "live_cytescore"}
)

pd.merge(demo_df, live_summary, on="scenario", how="outer")

,scenario,m,n,coverage,assignments,illustrative_cytescore,author_label,algorithm_label,author_ontology_name,algorithm_ontology_name,live_cytescore,similarity_method
0,2x1_coverage,2.0,1.0,0.5000,"[(1, 0)]",0.4600,AT2 cell-plasma cell doublet,Plasma cell,antibody secreting cell,antibody secreting cell,0.5000,cytescore_compound
1,2x2_one_overlap,2.0,2.0,1.0000,"[(0, 0), (1, 1)]",0.5300,AT2 cell-plasma cell doublet,AT2 cell / T cell,pulmonary alveolar type 2 cell;antibody secret...,pulmonary alveolar type 2 cell;T cell,0.5984,cytescore_compound
2,2x2_two_overlap,2.0,2.0,1.0000,"[(0, 0), (1, 1)]",0.9750,AT2 cell-plasma cell doublet,AT2 cell / Plasma cell,pulmonary alveolar type 2 cell;antibody secret...,pulmonary alveolar type 2 cell;antibody secret...,1.0000,cytescore_compound
3,2x2_zero_overlap,2.0,2.0,1.0000,"[(0, 0), (1, 1)]",0.0650,AT2 cell-plasma cell doublet,T cell / B cell,pulmonary alveolar type 2 cell;antibody secret...,T cell;B cell,0.3334,cytescore_compound
4,3x2_one_overlap,3.0,2.0,0.6667,"[(0, 0), (1, 1)]",0.3533,AT2 cell / plasma cell / NK cell,AT2 cell / T cell,pulmonary alveolar type 2 cell;natural killer ...,pulmonary alveolar type 2 cell;T cell,0.4121,cytescore_compound
5,simple_control,NaN,NaN,NaN,NaN,NaN,T cell,T cell,T cell,T cell,1.0000,cytescore

In [12]:
compound_df[compound_df["similarity_method"] == "cytescore_compound"][
    [
        "scenario",
        "author_ontology_id",
        "algorithm_ontology_id",
        "author_ontology_name",
        "algorithm_ontology_name",
        "cytescore_similarity",
    ]
]

,scenario,author_ontology_id,algorithm_ontology_id,author_ontology_name,algorithm_ontology_name,cytescore_similarity
0,2x1_coverage,CL:0000946,CL:0000946,antibody secreting cell,antibody secreting cell,0.5000
1,2x2_two_overlap,CL:0002063;CL:0000946,CL:0002063;CL:0000946,pulmonary alveolar type 2 cell;antibody secret...,pulmonary alveolar type 2 cell;antibody secret...,1.0000
2,2x2_one_overlap,CL:0002063;CL:0000946,CL:0002063;CL:0000084,pulmonary alveolar type 2 cell;antibody secret...,pulmonary alveolar type 2 cell;T cell,0.5984
3,2x2_zero_overlap,CL:0002063;CL:0000946,CL:0000084;CL:0000236,pulmonary alveolar type 2 cell;antibody secret...,T cell;B cell,0.3334
4,3x2_one_overlap,CL:0002063;CL:0000623,CL:0002063;CL:0000084,pulmonary alveolar type 2 cell;natural killer ...,pulmonary alveolar type 2 cell;T cell,0.4121

## Cache utilities

Artifacts are stored under `cyteonto/data/user_files/<run_id>/` keyed by provider and model (schema v3).

In [ ]:
cyto.cache_stats(run_id="quick_tutorial_demo")

In [14]:
# cyto.clear_run("quick_tutorial_demo")  # uncomment to delete cached files for this run